### ISSUE TITLE
Is there sender and receiver effect for valued ergm?

### ISSUE THREAD

**Issue by runnytone** [statnet/ergm.count#1]
Thanks for your contribution.
Is there sender and receiver effect for valued ergm?

**Comment by runnytone** [comment]
Thanks for your help. I find that nodeocovar and nodeicovar also work.

**Comment by krivit** [comment]
`nodeicovar` and `nodeocovar` are completely different in what they do, however: they are one-parameter statistics that are intended to represent positive correlation among values of edges incident on the same node.

**Comment by krivit** [comment]
More precisely, they also try to account for degree heterogeneity, but marginally rather than conditionally.

**Comment by krivit** [comment]
Fixed in statnet/ergm@7a67d2b16ae4e0e7410b2784ff52c83ab6bb575c.
