### ISSUE TITLE
Binomial-reference ERGM with multiple parameters

### ISSUE THREAD

**Issue by allenkei** [statnet/ergm.count#3]
Hi,

Thanks for the great package again!

The paper, Exponential-Family Random Graph Models for Valued Networks, provides a close form Poisson-reference ERGM with network sum as statistics. Just wondering for Binomial-reference ERGM, when \theta is a vector of multiple parameters for multiple network statistics, does Y_{ij} still follow a Binomial(m, logit^{-1}(\theta))? What is the distribution in close form for a Binomial-reference ERGM with multiple parameters?

Thank you so much in advance!
Allen

**Comment by krivit** [comment]
It will remain binomial for GLM-style effects: the ones that are dyad-independent terms for binary ERGMs.

**Comment by allenkei** [comment]
Dear Dr. Krivitsky,

Thank you very much and Merry Christmas!

Allen

**Comment by allenkei** [comment]
Dear Dr. Krivitsky,

Please forgive me to follow up with another question. I am writing to confirm if I have understand this correctly.

For a Binomial-reference valued ERGM with 2 network statistics,

<img width="600" alt="GithubBinomial" src="https://user-images.githubusercontent.com/11763232/103468290-70106100-4d0c-11eb-9eb1-fc3defd45d74.png">

that is each dyad in this network follows a Binomial distribution, with the same number of trials (m) and the probability of success in each trial is (\pi). Is this formulation correct for a Binomial-reference valued ERGM?

Thank you so much again and wish you a happy New Year!

Allen

**Comment by CarterButts** [comment]
@allenkei I would suggest directing these to the statnet help list, or contacting folks directly.  Posting these questions here sends them to everyone on the development team as software issues, which is not ideal.
