### ISSUE TITLE
Poisson-reference ERGM

### ISSUE THREAD

**Issue by allenkei** [statnet/ergm.count#4]
Dear Dr. Krivitsky,

I am writing to inquire about the Poisson-reference valued ERGM. 

The paper provides a dyadwise-independent Poisson distribution when the ERGM has only 1 network statistics: sum of all dyad values. I am wondering if you can expand a little on how to derive from the 2nd to 3rd term in the below equation?

<img width="500" alt="GithubQuestion" src="https://user-images.githubusercontent.com/11763232/103447623-87831780-4c42-11eb-8af8-1098a74f0ffa.png">

Also, for <img width="200" alt="GithubDistribution" src="https://user-images.githubusercontent.com/11763232/103447651-cdd87680-4c42-11eb-9274-260077d5b1fe.png">, I am wondering if the 3rd term would be <img width="150" alt="GithubCorrected" src="https://user-images.githubusercontent.com/11763232/103447780-79ce9180-4c44-11eb-8b9a-91b1aa5c57d3.png">

Thank you so much again and I have learned a lot from your paper. Wish you a happy New Year!

**Comment by CarterButts** [comment]
This doesn't seem to be a question about the package, but a statistical question.  I would recommend either contacting @krivit directly, or else posting to the statnet help mailing list about it - this isn't really the place for such discussion.
